# Generated by Django 3.2.4 on 2021-06-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_length', models.IntegerField()),
                ('Area_code', models.IntegerField()),
                ('Number_vmail_messages', models.IntegerField()),
                ('Total_day_minutes', models.IntegerField()),
                ('Total_day_calls', models.IntegerField()),
                ('Total_day_charge', models.IntegerField()),
                ('Total_eve_minutes', models.IntegerField()),
                ('Total_eve_calls', models.IntegerField()),
                ('Total_eve_charge', models.IntegerField()),
                ('Total_night_minutes', models.IntegerField()),
                ('Total_night_calls', models.IntegerField()),
                ('Total_night_charge', models.IntegerField()),
                ('Customer_service_calls', models.IntegerField()),
                ('Voice_mail_plan', models.IntegerField()),
                ('International_plan', models.IntegerField()),
                ('international_voice_call_usage', models.IntegerField()),
            ],
        ),
    ]
